version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd web_client
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: web_client/dist
    files:
      - '**/*'
  cache:
    paths:
      - web_client/node_modules/**/*
customHeaders:
  - pattern: '**/*'
    headers:
      - key: 'Cache-Control'
        value: 'public, max-age=31536000, immutable'
  - pattern: '/index.html'
    headers:
      - key: 'Cache-Control'
        value: 'no-cache, no-store, must-revalidate'
